### PR TITLE
Put the proper actions in receiver

### PR DESCRIPTION
**Pull request by Ethanol10**
The reason why it wasn't picking up the actions was because they were misnamed. This should work.

### CODE REVIEW

**Comment by Ethanol10** [comment]
I will ping you once I have tested this to work.

**Comment by Ethanol10** [comment]
Yeah, so I usually catch these but this time I forgot to push the changes in this file previously, so that's why it worked on my device, as I had those changes in the project tree but not in this PR.

I'll try not do that again haha

**Comment by Ethanol10** [comment]
```
2024-12-23 09:30:25.222  6212-6212  WIRELESS PEN CHARGER    pid-6212                             D  Received intent! Broadcaster should be working as expected. Action:android.intent.action.ACTION_POWER_DISCONNECTED
2024-12-23 09:30:25.222  6212-6212  WIRELESS PEN CHARGER    pid-6212                             D  Pen Charger turned off from unplugged event.
2024-12-23 09:30:27.998  6212-6212  WIRELESS PEN CHARGER    pid-6212                             D  Received intent! Broadcaster should be working as expected. Action:android.intent.action.ACTION_POWER_CONNECTED
2024-12-23 09:30:27.999  6212-6212  WIRELESS PEN CHARGER    pid-6212                             D  Pen Charger turned on from plugged in event.
```

Yup, it's working now. This is ready @Archfx !

**Comment by Archfx** [comment]
Great! Let me queue a release

**Pull request merged**
